### ISSUE TITLE
Why hasn't my pull request been merged yet ? 😡

### ISSUE THREAD

**Issue by stevebaros** [LeezaJee/portfolio.website#2]
So here iam ranting about why my pull request not being merged ! , 

could you give me reasons why ? 😀😀

**Comment by LeezaJee** [comment]
sorry for not getting back to you in the comment section before. I did not merge your pull request because I wanted to keep both buttons on my portfolio page for now. thanks a lot for your input anyway.

**Comment by stevebaros** [comment]
Okay fair enough 👍
